version: '3.8'
services:
  database:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    env_file:
      - .env
    container_name: 'spaceflight-db'
    networks:
      - spaceflight-network
    volumes:
      - 'database-volume:/var/lib/postgresql/data'
  api:
    container_name: spaceflight-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: "on-failure"
    ports:
      - '3000:3000'
    env_file:
      - .env
    networks:
      - spaceflight-network
    volumes:
      - '.:/opt/app'
    depends_on:
      - database
networks:
  spaceflight-network:
    name: spaceflight-network

volumes:
  database-volume:
